### ISSUE TITLE
Project Fit Discussion

### ISSUE THREAD

**Issue by Ben2012334** [spalladino/ethereum-upgrade-storage-free#8]
Hi @spalladino,

Reaching out here as I thought you might be interested in a challenging project involving SMPC, zk proofs, and scaling solutions. Your work stands out and looks like a strong match. 
If you’re open to a chat, feel free to reach me directly at benedykt@talentnetwork.io Thanks!

**Comment by spalladino** [comment]
Please don't use github for this.
